### ISSUE TITLE
TODO urgent

### ISSUE THREAD

**Issue by angost** [angost/Portfolio-Website#12]
- [x] buy, set up domain and ssl 
- [x] (almost) finish descriptions, tags, add better images
- [x] simple home page (photo?, about me, call to action (see my projects))
- [x] simple contact page (mail, linkedin)
- [x] fix scaling (on mobile, smaller web window)
        - add scroll to project details
        - move side panel to one column with title and description in project details when in narrow view
        - fix scaling cards
        - fix images not fitting at the bottom of project details
- [x] make email selectable text https://erengun.medium.com/making-texts-selectable-in-your-flutter-web-app-7e682931efd9
- [x] add nice linkedin link https://www.linkedin.com/badges/profile/create?vanityname=angelika-ostrowska-463b592b5&preferredlocale=pl_PL&trk=public_profile-settings_badge
